// Auto-generated by ProcedureKit Editor
// Do not modify this file manually

namespace SoyoFramework.Framework.Runtime. ProcedureKit.GeneratedClasses
{
    public enum ProcedureTag
    {
        ExampleTagA = 0,
        ExampleTagB = 1
    }
}
