// Auto-generated by ProcedureKit Editor
// Do not modify this file manually

using SoyoFramework.Framework. Runtime.ProcedureKit. DataClasses;

namespace SoyoFramework.Framework.Runtime.ProcedureKit. GeneratedClasses
{
    public enum ProcedureId
    {
        Entrance = 0,
        [ProcedureTags(ProcedureTag. ExampleTagA)]
        [AllowedPreviousProcedures(ProcedureId.Entrance, ProcedureId.ExampleProcedureB)]
        ExampleProcedureA = 1,
        [ProcedureTags(ProcedureTag. ExampleTagB)]
        [AllowedPreviousProcedures(ProcedureId.ExampleProcedureA)]
        ExampleProcedureB = 2
    }
}
