using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace SoyoFramework.OptionalKits.ProcedureKit.Editor.Window
{
    public partial class ProcedureKitEditorWindow
    {
        private void DrawRegion3_CodeGeneration()
        {
            EditorGUILayout.LabelField("代码生成设置", EditorStyles.boldLabel);
            EditorGUILayout.Space(10);

            // 生成路径
            EditorGUILayout.BeginHorizontal();
            EditorGUILayout.LabelField("生成路径", GUILayout.Width(120));
            _generatePath = EditorGUILayout.TextField(_generatePath);
            if (GUILayout. Button("浏览", GUILayout.Width(50)))
            {
                string selectedPath = EditorUtility.OpenFolderPanel("选择生成路径", "Assets", "");
                if (! string.IsNullOrEmpty(selectedPath))
                {
                    if (selectedPath.StartsWith(Application.dataPath))
                    {
                        _generatePath = "Assets" + selectedPath.Substring(Application.dataPath.Length);
                    }
                    else
                    {
                        EditorUtility.DisplayDialog("错误", "请选择项目 Assets 文件夹内的路径", "确定");
                    }
                }
            }

            EditorGUILayout.EndHorizontal();

            EditorGUILayout.Space(5);

            // 命名空间
            EditorGUILayout.BeginHorizontal();
            EditorGUILayout.LabelField("命名空间", GUILayout.Width(120));
            _namespace = EditorGUILayout.TextField(_namespace);
            EditorGUILayout.EndHorizontal();

            EditorGUILayout.Space(10);
            EditorGUILayout.LabelField("枚举名称设置", EditorStyles.boldLabel);
            EditorGUILayout.Space(5);

            // ProcedureId 枚举名
            EditorGUILayout.BeginHorizontal();
            EditorGUILayout.LabelField("ProcedureId 枚举名", GUILayout.Width(120));
            _procedureIdEnumName = EditorGUILayout. TextField(_procedureIdEnumName);
            EditorGUILayout.EndHorizontal();

            // ProcedureTag 枚举名
            EditorGUILayout.BeginHorizontal();
            EditorGUILayout.LabelField("ProcedureTag 枚举名", GUILayout.Width(120));
            _procedureTagEnumName = EditorGUILayout.TextField(_procedureTagEnumName);
            EditorGUILayout.EndHorizontal();

            EditorGUILayout.Space(20);

            // 生成预览
            EditorGUILayout.LabelField("生成预览", EditorStyles.boldLabel);
            EditorGUILayout.Space(5);

            EditorGUILayout.BeginVertical(EditorStyles.helpBox);
            EditorGUILayout.LabelField($"将生成以下文件到:  {_generatePath}");
            EditorGUILayout.Space(5);
            EditorGUILayout.LabelField($"  • {_procedureIdEnumName}. cs", EditorStyles.miniLabel);
            EditorGUILayout.LabelField($"  • {_procedureTagEnumName}.cs", EditorStyles.miniLabel);
            EditorGUILayout.LabelField($"  • ProcedureConfig.cs", EditorStyles.miniLabel);
            EditorGUILayout. LabelField($"  • ProcedureManager.cs", EditorStyles.miniLabel);
            EditorGUILayout.EndVertical();

            EditorGUILayout.Space(20);

            // 生成按钮
            bool hasErrors = _validationErrors.Count > 0;
            GUI.enabled = ! hasErrors;
            if (GUILayout.Button("生成 C# 类", GUILayout.Height(35)))
            {
                SaveToConfig();
                GenerateCSharpClasses();
            }

            GUI.enabled = true;

            if (hasErrors)
            {
                EditorGUILayout.HelpBox("存在验证错误，请先修复后再生成代码", MessageType.Warning);
            }
        }

        private void GenerateCSharpClasses()
        {
            if (! Directory.Exists(_generatePath))
                Directory.CreateDirectory(_generatePath);

            GenerateProcedureIdFile();
            GenerateProcedureTagFile();
            GenerateProcedureConfigFile();
            GenerateProcedureManagerFile();

            // 保存当前编辑数据的副本
            var savedTags = _tags.Select(t => new TagEntry { Name = t.Name, EnumValue = t.EnumValue }).ToList();
            var savedProcedures = _procedures.Select(p => new ProcedureEntry
            {
                Name = p.Name,
                EnumValue = p.EnumValue,
                TagEnumValues = new HashSet<int>(p.TagEnumValues),
                AllowedPreviousEnumValues = new List<int>(p.AllowedPreviousEnumValues)
            }).ToList();

            AssetDatabase. Refresh();

            // 恢复编辑数据
            _tags = savedTags;
            _procedures = savedProcedures;

            Debug.Log($"C# 类已生成到: {_generatePath}");
        }

        private void GenerateProcedureIdFile()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by ProcedureKit Editor");
            sb.AppendLine("// Do not modify this file manually");
            sb.AppendLine();
            sb.AppendLine($"namespace {_namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public enum {_procedureIdEnumName}");
            sb.AppendLine("    {");

            // 按 EnumValue 排序输出
            var sortedProcedures = _procedures.OrderBy(p => p.EnumValue).ToList();
            for (int i = 0; i < sortedProcedures. Count; i++)
            {
                var proc = sortedProcedures[i];
                string comma = i < sortedProcedures.Count - 1 ?  "," : "";
                sb. AppendLine($"        {proc.Name} = {proc.EnumValue}{comma}");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            string filePath = Path.Combine(_generatePath, $"{_procedureIdEnumName}.cs");
            File.WriteAllText(filePath, sb.ToString());
        }

        private void GenerateProcedureTagFile()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by ProcedureKit Editor");
            sb.AppendLine("// Do not modify this file manually");
            sb.AppendLine();
            sb.AppendLine($"namespace {_namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public enum {_procedureTagEnumName}");
            sb.AppendLine("    {");

            // 按 EnumValue 排序输出
            var sortedTags = _tags.OrderBy(t => t.EnumValue).ToList();
            for (int i = 0; i < sortedTags.Count; i++)
            {
                var tag = sortedTags[i];
                string comma = i < sortedTags.Count - 1 ? "," : "";
                sb.AppendLine($"        {tag.Name} = {tag.EnumValue}{comma}");
            }

            sb. AppendLine("    }");
            sb.AppendLine("}");

            string filePath = Path.Combine(_generatePath, $"{_procedureTagEnumName}.cs");
            File.WriteAllText(filePath, sb. ToString());
        }

        private void GenerateProcedureConfigFile()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by ProcedureKit Editor");
            sb.AppendLine("// Do not modify this file manually");
            sb.AppendLine();
            sb.AppendLine("using System. Collections.Generic;");
            sb.AppendLine("using System. Diagnostics. CodeAnalysis;");
            sb.AppendLine("using SoyoFramework.OptionalKits. ProcedureKit.Runtime. DataClasses;");
            sb.AppendLine();
            sb.AppendLine($"namespace {_namespace}");
            sb.AppendLine("{");
            sb.AppendLine(
                $"    public class ProcedureConfig : ProcedureConfig<{_procedureIdEnumName}, {_procedureTagEnumName}>");
            sb.AppendLine("    {");
            sb.AppendLine(
                $"        public override {_procedureIdEnumName} InitialProcedure {{ get; }} = {_procedureIdEnumName}. Entrance;");
            sb.AppendLine();
            sb.AppendLine("        [NotNull]");
            sb.AppendLine(
                $"        public override Dictionary<{_procedureIdEnumName}, MetaData> MetaDatas {{ get; }} = new()");
            sb.AppendLine("        {");

            // 按 EnumValue 排序输出
            var sortedProcedures = _procedures.OrderBy(p => p.EnumValue).ToList();
            for (int i = 0; i < sortedProcedures.Count; i++)
            {
                var proc = sortedProcedures[i];

                // 生成 Tags 数组
                string tagsArray;
                if (proc.TagEnumValues.Count > 0)
                {
                    var tagNames = proc.TagEnumValues
                        .OrderBy(ev => ev)
                        .Select(ev => _tags.FirstOrDefault(t => t.EnumValue == ev))
                        .Where(t => t != null)
                        .Select(t => $"{_procedureTagEnumName}.{t.Name}");
                    tagsArray = $"new {_procedureTagEnumName}[] {{ {string.Join(", ", tagNames)} }}";
                }
                else
                {
                    tagsArray = $"new {_procedureTagEnumName}[] {{ }}";
                }

                // 生成 AllowedPreviousProcedures 数组
                string allowedPrevArray;
                if (proc. AllowedPreviousEnumValues.Count > 0)
                {
                    var prevNames = proc.AllowedPreviousEnumValues
                        .Select(ev => _procedures.FirstOrDefault(p => p.EnumValue == ev))
                        . Where(p => p != null)
                        .Select(p => $"{_procedureIdEnumName}.{p.Name}");
                    allowedPrevArray = $"new {_procedureIdEnumName}[] {{ {string.Join(", ", prevNames)} }}";
                }
                else
                {
                    allowedPrevArray = $"new {_procedureIdEnumName}[] {{ }}";
                }

                string comma = i < sortedProcedures.Count - 1 ?  "," : "";

                sb.AppendLine("            {");
                sb.AppendLine($"                {_procedureIdEnumName}. {proc.Name},");
                sb.AppendLine("                new MetaData(");
                sb.AppendLine($"                    {tagsArray},");
                sb.AppendLine($"                    {allowedPrevArray}");
                sb.AppendLine("                )");
                sb. AppendLine($"            }}{comma}");
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            string filePath = Path.Combine(_generatePath, "ProcedureConfig.cs");
            File.WriteAllText(filePath, sb.ToString());
        }

        private void GenerateProcedureManagerFile()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by ProcedureKit Editor");
            sb.AppendLine("// Do not modify this file manually");
            sb.AppendLine();
            sb.AppendLine("using SoyoFramework.OptionalKits.ProcedureKit. Runtime.Core;");
            sb.AppendLine();
            sb.AppendLine($"namespace {_namespace}");
            sb.AppendLine("{");
            sb.AppendLine(
                $"    public interface IProcedureManager : IProcedureManager<{_procedureIdEnumName}, {_procedureTagEnumName}>");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine(
                $"    public class ProcedureManager : ProcedureManager<{_procedureIdEnumName}, {_procedureTagEnumName}>, IProcedureManager");
            sb.AppendLine("    {");
            sb.AppendLine("        private ProcedureManager(ProcedureConfig config) : base(config)");
            sb.AppendLine("        {");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static IProcedureManager CreateInstance()");
            sb.AppendLine("        {");
            sb.AppendLine("            var config = new ProcedureConfig();");
            sb.AppendLine("            return new ProcedureManager(config);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            string filePath = Path.Combine(_generatePath, "ProcedureManager.cs");
            File.WriteAllText(filePath, sb.ToString());
        }
    }
}