// Auto-generated by ProcedureKit Editor
// Do not modify this file manually

using SoyoFramework.Framework. Runtime.ProcedureKit. DataClasses;

namespace SoyoFramework.Framework.Runtime.ProcedureKit. GeneratedClasses
{
    public enum ProcedureId
    {
        Entrance = 0,
        [ProcedureTags(ProcedureTag. ExampleTag)]
        [AllowedPreviousProcedures(ProcedureId.Entrance)]
        ExampleProcedure = 1
    }
}
