// Auto-generated by ProcedureKit Editor
// Do not modify this file manually

using SoyoFramework.OptionalKits.ProcedureKit.Runtime.Core;

namespace SoyoFramework.OptionalKits.ProcedureKit.Example
{
    public interface IProcedureManager : IProcedureManager<ProcedureId, ProcedureTag>
    {
    }

    public class ProcedureManager : ProcedureManager<ProcedureId, ProcedureTag>, IProcedureManager
    {
        private ProcedureManager(ProcedureConfig config) : base(config)
        {
        }

        public static IProcedureManager CreateInstance()
        {
            var config = new ProcedureConfig();
            return new ProcedureManager(config);
        }
    }
}