// Auto-generated by ProcedureKit Editor
// Do not modify this file manually

namespace SoyoFramework.OptionalKits.ProcedureKit.Example
{
    public enum ProcedureId
    {
        Entrance = 0,
        ProcedureA = 1,
        ProcedureB = 100
    }
}
