// Auto-generated by ProcedureKit Editor
// Do not modify this file manually

namespace SoyoFramework.OptionalKits.ProcedureKit.Example
{
    public enum ProcedureTag
    {
        TagX = 0,
        TagY = 1
    }
}
