// Auto-generated by ProcedureKit Editor
// Do not modify this file manually

namespace SoyoFramework.Examples.Test_Procedure
{
    public enum ProcedureTag
    {
        TagX = 0,
        TagY = 1
    }
}
