// Auto-generated by ProcedureKit Editor
// Do not modify this file manually

namespace SoyoFramework.Examples.Test_Procedure
{
    public enum ProcedureId
    {
        Entrance = 0,
        ProcedureA = 1,
        ProcedureB = 100
    }
}
